spring.application.name=aws-dynamodb-vector-search
app.aws.dynamo-db.table-name=ArxivPaperVectorStore
app.aws.dynamo-db.index-name=PaperVectorIndex
app.aws.bedrock-properties.model-id=amazon.titan-embed-text-v2:0
app.aws.bedrock-properties.dimensions=1024
app.aws.bedrock-properties.distance-function=COSINE
app.aws.bedrock-properties.max-embed-chars=20000
app.aws.dataset.url=https://huggingface.co/datasets/gfissore/arxiv-abstracts-2021/resolve/main/arxiv-abstracts.jsonl.gz
app.aws.dataset.sample-size=1000